### PR TITLE
Addeded basic keyboard shortcut X for Pan and C for Claim

### PR DESCRIPTION
**Pull request by luntdotp**

### CODE REVIEW

**Comment by codeThatThinks** [comment]
Are we able to do plus and minus keys for zoom in/out?

**Comment by luntdotp** [comment]
Working on plus and minus, I have 1 and 2 for zoom at the moment. Will pull request when I can.

**Comment by codeThatThinks** [comment]
It's probably a good idea that we implement zooming with the scroll wheel too. Seems like a really easy thing to do with jQuery: [http://stackoverflow.com/questions/3715496/binding-to-the-scroll-wheel-when-over-a-div](http://stackoverflow.com/questions/3715496/binding-to-the-scroll-wheel-when-over-a-div).

**Comment by luntdotp** [comment]
I had a quick go at using scrolling but it didn't seem to work. Will try again later.

**Pull request merged**
